#define NO_PRESET_TEXT "DEFAULT"
#define PRESET_ONE_TEXT "PRESET1"
#define PRESET_TWO_TEXT "PRESET2"

#define LIGHT_ONE_TEXT "A"
#define LIGHT_TWO_TEXT "B"
#define LIGHT_THREE_TEXT "C"
#define LIGHT_FOUR_TEXT "D"

#define PWM0_TEXT "PWM0"
#define PWM1_TEXT "PWM1"

#define PWM_NONE_SELECTED "NONE"
#define PWM_ZERO_SELECTED "PWM0"
#define PWM_ONE_SELECTED "PWM1"

#define MASTER_BUTTON_TEXT "MASTER"
